Parameters:
  NameOfService:
    Description: Name your instance
    Type: String
  KeyName:
    Description: Choose your KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Mappings:
  RegionMap:
    us-east-1:
      AmiUbuntu2204: ami-06878d265978313ca
      AmiAmazonLinux2: ami-0b5eea76982371e91
    eu-south-2:
      AmiUbuntu2204: ami-06a35994aaed77af8
      AmiAmazonLinux2: ami-0da857776d374a2fe

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !FindInMap [ RegionMap, !Ref AWS::Region, AmiAmazonLinux2 ]
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd.x86_64
            systemctl start httpd.service
            systemctl enable httpd.service
            echo "Hello World from $(hostname -f)" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Ref NameOfService

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group created for a Web Server
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
Outputs:
  ServerDns:
    Value: !GetAtt MyEC2Instance.PublicDnsName
