Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-06878d265978313ca # Ubuntu 22.04 amd64 AMI in us-east-1
      Tags:
        - Key: Name
          Value: My first EC2 instance using CloudFormation
      SecurityGroups:
        - !Ref NewSecurityGroup
  NewSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: New Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: New Security Group